pipeline {
    environment { 

        registry = "devopshint/my-app-1.0" 

        registryCredential = 'devopshint' 

    }

    agent any
    stages {
        stage('Cloning our Git') { 

            steps { 

                git 'https://github.com/devopshint/jenkins-maven.git' 

            }

        } 
    }
}
