pipeline {
    environment { 

        registry = "devopshint/my-app-1.0" 

        registryCredential = 'devopshint' 

    }

    agent any
    stages {
        stage('Cloning our Git') { 
10
            steps { 
11
                git 'https://github.com/devopshint/jenkins-maven.git' 
12
            }
13
        } 
     stage('Building our image') { 

            steps { 

                script { 

                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 

                }

            } 
        }

     }
     
}
